# Generated by Django 5.2.1 on 2025-08-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
