# Generated by Django 5.2.1 on 2025-07-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
