# Generated by Django 5.2.1 on 2025-08-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobmodel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
