# Generated by Django 5.2.6 on 2025-09-28 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobmodel_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='skill',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.resumemodel'),
        ),
    ]
