# Generated by Django 6.0.7 on 2026-09-01 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobmodel_skill_alter_jobmodel_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='score',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='score_description',
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='skill',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.SmallIntegerField(blank=True, null=True)),
                ('score_description', models.TextField(blank=True, default='')),
                ('cover_letter', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobmodel')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.resumemodel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('resume', 'job'), name='unique_resume_job_application')],
            },
        ),
    ]
