# Generated by Django 6.0.7 on 2026-09-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_resume_info_resumemodel_resume_info_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumemodel',
            name='experience_summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
