# Generated by Django 6.0.7 on 2026-09-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_resumemodel_experience_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='skill',
            new_name='skills',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
    ]
