# Generated by Django 6.0.7 on 2026-09-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_rename_skill_jobmodel_skills_jobmodel_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected'), ('hired', 'Hired'), ('checking', 'Checking')], default='checking', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
