# Generated by Django 6.0.7 on 2026-09-21 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_applicationmodel_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='jobs.jobmodel'),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_applications', to='jobs.resumemodel'),
        ),
    ]
