# Generated by Django 4.2 on 2025-05-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resume',
            new_name='ResumeModel',
        ),
    ]
