# Generated by Django 4.2 on 2025-05-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_rename_resume_resumemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumemodel',
            old_name='resume_file',
            new_name='file',
        ),
    ]
