# Generated by Django 5.2.1 on 2025-05-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_rename_resume_file_resumemodel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumemodel',
            name='linkedin_url',
        ),
    ]
