# Generated by Django 5.2.1 on 2025-05-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_remove_resumemodel_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumemodel',
            name='resume_info',
            field=models.JSONField(default=dict),
        ),
    ]
